language: java
branches:
  only:
  - "/^v1.*$/"
env:
  global:
  - secure: oCoqoUdxOxyVUae9OLJH/hR+YIsvaH/lOxbA+nEM68NxbfrT/brWFvneWzi199ExbFm/ZgCfIPVM5BCA8OUCT4J2yulPmckYEfVy5IIX3JXyikMLmLUB0il6s8GfSbzfZCGEA/gFwVeE3EB/fscxkCzF/5VxycKefiOYHrMQMWI=
notifications:
  email: false
before_install:
- mvn -f coreprotect.xml install
- mvn versions:set -DnewVersion=${TRAVIS_TAG:1}
deploy:
  provider: releases
  api-key: "${GITHUB_TOKEN}"
  file:
  - target/XRayHunter.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
cache:
  directories:
  - "$HOME/.m2"
